continuation_prompt = "[â¯](bold white)"

format = """
[îƒ‘](bg:#c4265e fg:#ae81ff)\
$localip$hostname$username\
[î‚°](bg:#212736 fg:#c4265e)\
$container\
$nodejs\
$rust\
$golang\
$php\
$python\
$conda\
[î‚´](fg:#212736 bg:#a3aed2)\
[î‚´](fg:#a3aed2 bg:#ff8000)\
$battery$custom\
[î‚´ ](fg:#ff8000)\
$docker_context$package$buf$c$cmake$cobol$dart$deno$dotnet$elixir$elm$erlang$haskell$helm$java$julia$kotlin$lua$nim$ocaml$perl$pulumi$purescript$rlang$red$ruby$scala$swift$terraform$vlang$vagrant$zig$nix_shell$spack$memory_usage$aws$gcloud$openstack$azure$env_var$crystal\

\n\
[ îœ‘ ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\

\n\
$character"""
right_format = '''$jobs$cmd_duration'''

# first -------------------------------------------------------------------------------------
[custom.aabb]
symbol = "ğŸ”‹"
style  = "fg:#e3e5e5 bg:#ff8000"
format  = '[($output)%]($style)'
command = 'cat /sys/class/power_supply/battery/capacity'
use_stdin = true
detect_folders = ['.config']

[localip]
style = "fg:#e3e5e5 bg:#c4265e"
ssh_only = false
format = '[ ï†˜ $localipv4 ]($style)'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[:$user ]($style bg:#c4265e)'
disabled = false
show_always = true

[hostname]
ssh_only = true
ssh_symbol = "ğŸ›¸"
style = "fg:#e3e5e5 bg:#c4265e"
format = '[$ssh_symbol $hostname]($style)'
trim_at = '.companyname.com'
detect_env_vars = ['!notshow', 'SSH_CONNECTION']
disabled = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’§"
# format = '[$symbol$percentage]($style) '
format = "[ $symbol]($style)"
disabled = false
[[battery.display]]
threshold = 10
style = "fg:#e3e5e5 bg:#ff8000"

# second -------------------------------------------------------------------------------------
[directory]
style = "fg:#000000 bg:#769ff0"
truncation_length = 5
read_only="ï€£"
read_only_style="fg:#c4265e bg:#769ff0"
truncation_symbol = "â€¦/"
format="[ $read_only]($read_only_style)[ $path ]($style)"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'


[time]
disabled = false
time_format = "%m-%d %R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'


[character]
success_symbol="[â¯](bold green)"
error_symbol="[â¯](bold red)"
vicmd_symbol="[â®](bold green)"


# right_format
[jobs]
symbol = "âœ¦"
# style = "fg:blue bg:#ffb86c"
number_threshold = 2
symbol_threshold = 1
format = "[$symbol$number]($style)"

[cmd_duration]
format = '[\[$duration\]](yellow)'
min_time = 1
show_milliseconds = true


# code environment
[container]
symbol = "ï’¦"
style = "bg:#212736"
format = '[[ $symbol ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[conda]
style = "bg:#212736"
format = '[[ $symbol ($environment) ](fg:#769ff0 bg:#212736)]($style)'
